### ISSUE TITLE
Beanstalkd error with docker-compose

### ISSUE THREAD

**Issue by SGarridoDev** [schickling/dockerfiles#107]
Hi,
I need to execute beanstalkd with docker-compose and I got this error:

> /usr/bin/beanstalkd: unknown argument: beanstalkd

My docker-compose.yml code:
> version: '3.1'
services:
    beanstalkd:
        image: schickling/beanstalkd
        volumes:
            - beanstalk-data:/data
        command: beanstalkd -p 11300 -b /data
        depends_on:
          - php
    beanstalkd-console:
      image: schickling/beanstalkd-console
      ports:
        - 2080:2080
      environment:
        BEANSTALKD_PORT_11300_TCP_ADDR: beanstalkd
      links:
        - beanstalkd

I need any help with this.
Thanks in advance and good work @schickling

**Comment by OlivierCuyp** [comment]
Hi, as you can see in the Dockerfile `beanstalk` is already specify as **ENTRYPOINT**.
here: https://github.com/schickling/dockerfiles/blob/master/beanstalkd/Dockerfile#L7
So you don't need to put it in your command, change your command to this:

```yml
command: "-p 11300 -b /data"
```

I hope, it helped.

**Comment by SGarridoDev** [comment]
Hi @OlivierCuyp,

Your solution works fine!

Thanks!
