### ISSUE TITLE
mysql-backup-s3 rotate back-ups

### ISSUE THREAD

**Issue by SolveSoul** [schickling/dockerfiles#108]
It would be great if it would be possible to rotate the back-ups. There are 3 scenario's and only 2 are covered so far.

- Write back-up to S3 as new file
- Write back-up to S3 and overwrite previous back-up

Now the last scenario I'd find useful would be:
- Back-up every _x_ days/hours/... and when _n_-amount of back-ups are reached, throw away the oldest back-up and add the newest.

This scenario would enable us to keep for example 3 versions. This scenario doesn't flood the bucket with really old data but also prevents the latest back-up being overwritten with data you wanted to keep.

```
For example:
Day 1: back-up created
Day 2: back-up overwritten
Day 3: back-up overwritten
Day 4: something goes terribly wrong with the data > back-up overwritten > notices data is corrupt after the back-up.
```

If using the overwrite mode there is no way to go back to the data of day 3.

**Comment by OlivierCuyp** [comment]
@SolveSoul Can't you use the env var `S3_FILENAME` to have the overwrite ?

**Comment by SolveSoul** [comment]
> @SolveSoul Can't you use the env var `S3_FILENAME` to have the overwrite ?

I can use that to overwrite the file daily but then I still won't have a history of _n_-amount back-ups. Or am I misinterpreting what you're trying to say?

**Comment by OlivierCuyp** [comment]
Usually I enable versioning on the Lifecycle of the S3 Bucket when doing this.
There you can even specify the retention duration.
Won't this solve your issue ?

**Comment by SolveSoul** [comment]
Yes, you're correct. I'm not that familiar with S3. I configured the bucket's lifecycle and will evaluate it's deletion behaviour. 

Thanks for helping out!
