### ISSUE TITLE
postgres-backup-s3: V11 not supported

### ISSUE THREAD

**Issue by ledermann** [schickling/dockerfiles#115]
Backing up a PostgreSQL v11.2 database fails. From the logs:

```
2019/03/31 00:00:00 17 cmd: /bin/sh backup.sh
2019/03/31 00:00:00 17: Creating dump of example database from db...
2019/03/31 00:00:00 17: pg_dump: 
2019/03/31 00:00:00 17: server version: 11.2; pg_dump version: 10.4
2019/03/31 00:00:00 17: pg_dump: 
2019/03/31 00:00:00 17: aborting because of server version mismatch
2019/03/31 00:00:00 17 Exit Status: 1
```

It seems that the Docker image is a bit outdated and should be rebuild.

**Comment by darklow** [comment]
Having same issue, it would be great to have updated build on here https://hub.docker.com/r/schickling/mysql-backup-s3
Thanks.

**Comment by itbm** [comment]
> Having same issue, it would be great to have updated build on here https://hub.docker.com/r/schickling/mysql-backup-s3
> Thanks.

Had the same problem, as the image hadn't been updated in a year I built my own image https://hub.docker.com/r/itbm/postgresql-backup-s3

**Comment by karser** [comment]
I have added Postgres v12.4 support https://hub.docker.com/r/karser/postgres-backup-s3
Here is the repo https://github.com/karser/docker-images/tree/master/postgres-backup-s3
