### ISSUE TITLE
curl downloads with --insecure parameter

### ISSUE THREAD

**Issue by onitake** [schickling/dockerfiles#142]
In https://github.com/schickling/dockerfiles/blob/master/postgres-backup-s3/install.sh#L17 , curl is executed with the `--insecure` parameter.

Is there a specific reason for this?
Downloading from Github surely shouldn't produce any HTTPS certificate errors?

Removing the parameter works fine for me.

**Comment by iloveitaly** [comment]
@onitake I don't think so. Want to submit a PR updating the dockerfiles?

**Comment by onitake** [comment]
There you go :wink:
