### ISSUE TITLE
Build dockerfiles with `arm` compatibility

### ISSUE THREAD

**Issue by jdecool** [schickling/dockerfiles#144]
Some of your Docker images are the most used on Docker Hub 👏🏼 

It could be interesting to build them for `arm` architecture (for better Mac M1 compatibility).

**Comment by iloveitaly** [comment]
That would be great! Want to submit a PR to support?

**Comment by jdecool** [comment]
I can't because the target platform should be specify when the image is build.

And the build code is not a part of the repository.

**Comment by jdecool** [comment]
Images should be build with `docker buildx`:

```bash
docker buildx build \
    --push \
    --platform linux/arm64,linux/amd64 \
    -t [tag] \
    path/to/Dockerfile
```

**Comment by iloveitaly** [comment]
It would be great if we could add a build script to this repo to execute
this across all dockerfiles in the repo.

**Comment by jdecool** [comment]
@iloveitaly I've opened #145 

Tell me if it's what you talked about

**Comment by iloveitaly** [comment]
This is done! I've updated some of the images on docker hub too.
