### ISSUE TITLE
S3_ENDPOINT strange

### ISSUE THREAD

**Issue by lbcd** [schickling/dockerfiles#161]
Hello,

I'm tryiong to use to backup mysql on a S3 like.

I have this env var
S3_ENDPOINT: "https://s3.rbx.io.cloud.ovh.net/"

And here is what I get as log: 
Creating individual dump of xxxx from mysql.xxxxx...
Ensuring S3 bucket backup exists
Bucket backup not found (or owned by someone else), attempting to create
Could not connect to the endpoint URL: "https://**s3.rbx.amazonaws.com**/"

How it is possible that program changes s3.rbx.io.cloud.ovh.net to  s3.rbx.amazonaws.com ???

Thanks in advance

**Comment by lbcd** [comment]
I found the issue. I didn't put S3_REGION and let default value.
So with the region
  S3_REGION: "rbx"

It works.

Thx for this docker image!

**Comment by iloveitaly** [comment]
Want to submit a PR to improve the documentation here?
