### ISSUE TITLE
swagger-ui: the URL to swagger.json in index.html should be relative

### ISSUE THREAD

**Issue by EvgenyOrekhov** [schickling/dockerfiles#30]
I use a reverse proxy and I use http://domain**/docs/** as the base URL for swagger-ui. The reverse proxy forwards all /docs/* requests to swagger-ui, and swagger-ui is receiving all requests stripped off of /docs/.
The [run.sh](https://github.com/schickling/dockerfiles/blob/d967110208c9e3f06e11643d516c51c7bf615664/swagger-ui/run.sh#L12-L13) uses /swagger.json (with a leading slash) as the URL in index.html, so swagger-ui ends up making a request to http://domain/swagger.json, and I have to serve an additional swagger.json file using my reverse proxy.
If we change the URL to swagger.json it will fix my issue and swagger-ui will make the request to http://domain/docs/swagger.json, it will decouple my reverse proxy and swagger-ui.
The ones who serve swagger-ui under the root path will not be affected.

Would you accept the pull request if I change /swagger.json to swagger.json in [run.sh](https://github.com/schickling/dockerfiles/blob/d967110208c9e3f06e11643d516c51c7bf615664/swagger-ui/run.sh#L12-L13)?

**Comment by schickling** [comment]
The point you're making sounds reasonable to me. I'm no longer using swagger myself, so I cannot say whether it affects people or not. I'd say let's give it a shot. In the worst-case we rollback and look for a different approach.
