### ISSUE TITLE
swagger-ui: Ability to set custom validator URL

### ISSUE THREAD

**Issue by kbedel** [schickling/dockerfiles#35]
I want to be able to override the validatorUrl property to point to a custom validator. In my case, this is a container created from the swaggerapi/swagger-validator image.

I can submit a PR for this.

**Comment by schickling** [comment]
Is this a breaking change or a very specific requirement for your case?

**Comment by kbedel** [comment]
It wouldn't be breaking, it would just be an additional sed command in the run.sh to set the validatorUrl parameter in index.html if the environment variable is set. I think this would be useful for anyone wanting to use Swagger UI against a non-public service which can't be reached from the public online Swagger validator.

[Swagger-ui readme](https://github.com/swagger-api/swagger-ui) has information about the validatorUrl parameter.

**Comment by schickling** [comment]
Okay cool! Go for it. Happy to merge a PR on this! 👍
