### ISSUE TITLE
Undefined $S3_PREFIX results in nameless directory in s3

### ISSUE THREAD

**Issue by willdady** [schickling/dockerfiles#59]
As per the title, by not setting `S3_PREFIX` I assumed all backups would go into the root of my dedicated backup bucket however the backup files end up under an unnamed directory when viewing the AWS S3 console.

`cat dump.sql.gz | aws s3 cp - s3://$S3_BUCKET/$S3_PREFIX/$(date +"%Y-%m-%dT%H:%M:%SZ").sql.gz || exit 2`

I assume the extraneous `/` needs to be removed if `$S3_PREFIX` isn't provided.

**Comment by schickling** [comment]
Would you mind providing a PR for this?

**Comment by acim** [comment]
It would be also nice to have date as S3_PREFIX, for example value of "date --rfc-3339=date" output.
