### ISSUE TITLE
How to make mysql-backup-s3  execute backup with no wait

### ISSUE THREAD

**Issue by Yaowenjie** [schickling/dockerfiles#74]
Hi there,

`mysql-backup-s3` is good tool for backup mysql data. But sometimes, we just want to backup the data to S3 at once without waiting. Is there any way to execute the backup immediately?

Thanks

**Comment by soarhevn** [comment]
1. Get into the container: `docker exec -it [container_name] /bin/sh`
2. Make the `backup.sh` file executable: `chmod u+x backup.sh`
3. Call the script: `./backup.sh`
